// src/data.js
export const mockData = {
  organizations: [
    {
      name: 'PG Bears',
      ageGroups: [
        { name: '6U', players: 12 },
        { name: '8U', players: 18 },
        { name: '10U', players: 16 },
        { name: '12U', players: 20 },
        { name: '14U', players: 19 },
      ],
      games: [
        {
          id: 'pgb-1',
          ageGroup: '10U',
          matchup: 'PG Bears vs Flight School',
          date: '2025-10-18',
          time: '13:00',
          location: 'National Harbor, MD',
          notes: "Arrive 30 minutes early and bring all equipment and ID's.",
        },
        {
          id: 'pgb-2',
          ageGroup: '10U',
          matchup: 'PG Bears vs Marlboro Lions',
          date: '2025-10-11',
          time: '13:00',
          location: 'National Harbor, MD',
          notes: 'Home game — uniform check required.',
        },
        {
          id: 'pgb-3',
          ageGroup: '8U',
          matchup: 'PG Bears vs Bowie Eagles',
          date: '2025-09-15',
          time: '10:30',
          location: 'Bowie Sports Complex, MD',
          notes: 'Bring snacks and water bottles.',
        },
        {
          id: 'pgb-4',
          ageGroup: '6U',
          matchup: 'PG Bears vs Forestville Cubs',
          date: '2025-11-02',
          time: '09:00',
          location: 'PG Mini Field, MD',
          notes: 'Family fun day event after the game.',
        },
        {
          id: 'pgb-5',
          ageGroup: '12U',
          matchup: 'PG Bears vs Oxon Hill Kings',
          date: '2025-10-27',
          time: '15:00',
          location: 'Oxon Hill Stadium, MD',
          notes: 'Away game — meet at 1:30 PM for travel.',
        },
      ],
    },
    {
      name: 'Panthers',
      ageGroups: [
        { name: '6U', players: 10 },
        { name: '8U', players: 14 },
        { name: '10U', players: 17 },
        { name: '12U', players: 19 },
      ],
      games: [
        {
          id: 'pan-1',
          ageGroup: '8U',
          matchup: 'Panthers vs Silver Spring Sharks',
          date: '2025-10-19',
          time: '12:00',
          location: 'Silver Spring Park, MD',
          notes: 'Wear black uniforms.',
        },
        {
          id: 'pan-2',
          ageGroup: '10U',
          matchup: 'Panthers vs Laurel Lightning',
          date: '2025-10-05',
          time: '14:00',
          location: 'Laurel Turf Field, MD',
          notes: 'Bring team IDs for verification.',
        },
        {
          id: 'pan-3',
          ageGroup: '6U',
          matchup: 'Panthers vs PG Bears',
          date: '2025-09-21',
          time: '10:00',
          location: 'Panthers Home Field, MD',
          notes: 'Friendly match — no scoring.',
        },
        {
          id: 'pan-4',
          ageGroup: '12U',
          matchup: 'Panthers vs Waldorf Wolves',
          date: '2025-10-29',
          time: '16:30',
          location: 'Waldorf Stadium, MD',
          notes: 'Travel by bus, check-in 2 hours before.',
        },
      ],
    },
    {
      name: 'Capital Cougars',
      ageGroups: [
        { name: '8U', players: 13 },
        { name: '10U', players: 16 },
        { name: '12U', players: 21 },
      ],
      games: [
        {
          id: 'cc-1',
          ageGroup: '10U',
          matchup: 'Capital Cougars vs Greenbelt Hawks',
          date: '2025-10-10',
          time: '12:30',
          location: 'Capital Sports Dome, DC',
          notes: 'Indoor match — bring turf shoes only.',
        },
        {
          id: 'cc-2',
          ageGroup: '12U',
          matchup: 'Capital Cougars vs Baltimore Bulls',
          date: '2025-11-03',
          time: '17:00',
          location: 'Baltimore Arena, MD',
          notes: 'Championship Qualifier Round.',
        },
        {
          id: 'cc-3',
          ageGroup: '8U',
          matchup: 'Capital Cougars vs Fairfax Foxes',
          date: '2025-09-28',
          time: '11:15',
          location: 'Fairfax Park, VA',
          notes: 'Bring ID & team lanyard.',
        },
      ],
    },
    {
      name: 'Riverdale Raiders',
      ageGroups: [
        { name: '6U', players: 11 },
        { name: '8U', players: 15 },
        { name: '10U', players: 19 },
        { name: '14U', players: 22 },
      ],
      games: [
        {
          id: 'rr-1',
          ageGroup: '14U',
          matchup: 'Riverdale Raiders vs Bowie Eagles',
          date: '2025-10-13',
          time: '16:00',
          location: 'Bowie Fieldhouse, MD',
          notes: 'Semifinal game — bring both uniforms.',
        },
        {
          id: 'rr-2',
          ageGroup: '10U',
          matchup: 'Riverdale Raiders vs Panthers',
          date: '2025-09-20',
          time: '14:00',
          location: 'Riverdale Field, MD',
          notes: 'Homecoming game — parents invited!',
        },
        {
          id: 'rr-3',
          ageGroup: '8U',
          matchup: 'Riverdale Raiders vs PG Bears',
          date: '2025-10-21',
          time: '12:30',
          location: 'PG Sports Center, MD',
          notes: 'Friendly match.',
        },
      ],
    },
    {
      name: 'Waldorf Wolves',
      ageGroups: [
        { name: '8U', players: 12 },
        { name: '10U', players: 15 },
        { name: '12U', players: 18 },
      ],
      games: [
        {
          id: 'ww-1',
          ageGroup: '10U',
          matchup: 'Waldorf Wolves vs Panthers',
          date: '2025-10-29',
          time: '16:30',
          location: 'Waldorf Stadium, MD',
          notes: 'Travel bus leaves 2:30 PM sharp.',
        },
        {
          id: 'ww-2',
          ageGroup: '8U',
          matchup: 'Waldorf Wolves vs Oxon Hill Kings',
          date: '2025-09-13',
          time: '09:30',
          location: 'Waldorf Community Field, MD',
          notes: 'Opening day ceremony.',
        },
        {
          id: 'ww-3',
          ageGroup: '12U',
          matchup: 'Waldorf Wolves vs Laurel Lightning',
          date: '2025-11-05',
          time: '17:30',
          location: 'Laurel Turf Field, MD',
          notes: 'Final game of the season.',
        },
      ],
    },
  ],
};
